include common.mk

MAPNIK_LIBS = $(shell mapnik-config --libs)

libmapnik-jni.jnilib: $(SOURCE_DEPENDS)
	$(CXX) -o libmapnik-jni.jnilib -undefined dynamic_lookup -bundle \
		$(CFLAGS) \
		$(MAPNIK_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		$(MAPNIK_LIBS) -framework JavaVM
	
clean:
	rm libmapnik-jni.jnilib
	

