include common.mk

MAPNIK_LIBS = $(shell mapnik-config --libs --ldflags --dep-libs)

libmapnik-jni.so: $(SOURCE_DEPENDS)
	$(CXX) -o libmapnik-jni.so \
		-fPIC -shared \
		$(CFLAGS) \
		$(MAPNIK_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		-lpython2.7 -lboost_python -I/usr/include/python2.7 \
		$(MAPNIK_LIBS)
	
clean:
	rm libmapnik-jni.so
	
